# Generated by Django 5.2.3 on 2025-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full', 'Full Sync'), ('dandisets', 'Dandisets Only'), ('assets', 'Assets Only')], default='full', max_length=20)),
                ('last_sync_timestamp', models.DateTimeField(help_text='When the last sync was completed')),
                ('dandisets_synced', models.IntegerField(default=0, help_text='Number of dandisets synced')),
                ('assets_synced', models.IntegerField(default=0, help_text='Number of assets synced')),
                ('dandisets_updated', models.IntegerField(default=0, help_text='Number of dandisets updated')),
                ('assets_updated', models.IntegerField(default=0, help_text='Number of assets updated')),
                ('sync_duration_seconds', models.FloatField(default=0.0, help_text='Duration of sync in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
