# Generated by Django 5.2.3 on 2025-06-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0002_add_sync_tracker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synctracker',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at'], 'verbose_name': 'Synchronization Record', 'verbose_name_plural': 'Synchronization Records'},
        ),
        migrations.AddField(
            model_name='synctracker',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if sync failed', null=True),
        ),
        migrations.AddField(
            model_name='synctracker',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', help_text='Status of the sync operation', max_length=20),
        ),
    ]
