# Generated by Django 5.2.3 on 2025-06-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0003_add_sync_tracker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by_sync',
            field=models.ForeignKey(blank=True, help_text='Sync operation that created this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to='dandisets.synctracker'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_modified_by_sync',
            field=models.ForeignKey(blank=True, help_text='Last sync operation that modified this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_modified', to='dandisets.synctracker'),
        ),
        migrations.AddField(
            model_name='dandiset',
            name='created_by_sync',
            field=models.ForeignKey(blank=True, help_text='Sync operation that created this dandiset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dandisets_created', to='dandisets.synctracker'),
        ),
        migrations.AddField(
            model_name='dandiset',
            name='last_modified_by_sync',
            field=models.ForeignKey(blank=True, help_text='Last sync operation that modified this dandiset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dandisets_modified', to='dandisets.synctracker'),
        ),
    ]
