# Generated by Django 5.2.3 on 2025-06-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0004_add_sync_tracking_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='include_in_citation',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='role_name',
        ),
        migrations.AddField(
            model_name='dandisetcontributor',
            name='include_in_citation',
            field=models.BooleanField(default=True, help_text='Include contributor in citation for this dandiset'),
        ),
        migrations.AddField(
            model_name='dandisetcontributor',
            name='role_name',
            field=models.JSONField(blank=True, default=list, help_text='Role(s) of the contributor in this specific dandiset'),
        ),
    ]
