# Generated by Django 5.2.3 on 2025-06-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0005_remove_contributor_include_in_citation_and_more'),
    ]

    operations = [
    ]
