# Generated by Django 5.2.3 on 2025-06-17 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0006_auto_20250616_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='synctracker',
            name='lindi_metadata_processed',
            field=models.IntegerField(default=0, help_text='Number of LINDI metadata records processed'),
        ),
        migrations.AlterField(
            model_name='synctracker',
            name='sync_type',
            field=models.CharField(choices=[('full', 'Full Sync'), ('dandisets', 'Dandisets Only'), ('assets', 'Assets Only'), ('lindi', 'LINDI Metadata Only')], default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='LindiMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_metadata', models.JSONField(help_text='LINDI generation metadata')),
                ('structure_metadata', models.JSONField(help_text='Filtered LINDI refs structure (no base64 data)')),
                ('lindi_url', models.URLField(help_text='URL to the original LINDI file')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_version', models.CharField(default='1.0', max_length=20)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lindi_metadata', to='dandisets.asset')),
                ('sync_tracker', models.ForeignKey(blank=True, help_text='Sync operation that processed this LINDI metadata', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lindi_metadata_created', to='dandisets.synctracker')),
            ],
            options={
                'verbose_name': 'LINDI Metadata',
                'verbose_name_plural': 'LINDI Metadata',
                'ordering': ['-processed_at'],
            },
        ),
    ]
