# Generated by Django 5.2.3 on 2025-06-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0007_add_lindi_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lindimetadata',
            name='generation_metadata',
        ),
        migrations.AlterField(
            model_name='lindimetadata',
            name='structure_metadata',
            field=models.JSONField(help_text='Filtered LINDI structure (no base64 data or large arrays)'),
        ),
    ]
