# Generated by Django 5.2.3 on 2025-06-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dandisets', '0008_update_lindi_metadata_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['dandi_asset_id']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='path',
        ),
        migrations.AddField(
            model_name='assetdandiset',
            name='path',
            field=models.TextField(default='', help_text='Path to the asset within this specific dandiset'),
        ),
    ]
